/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Generic error envelope returned by failing endpoints.
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     * Human-readable error message safe to display to the user
     * @type {string}
     * @memberof ApiError
     */
    error: string;
    /**
     * For 429 responses: seconds the client should wait before retrying.
     * Mirrors the value of the `Retry-After` header.
     * 
     * @type {number}
     * @memberof ApiError
     */
    retryAfterSeconds?: number;
}

/**
 * Check if a given object implements the ApiError interface.
 */
export function instanceOfApiError(value: object): value is ApiError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ApiErrorFromJSON(json: any): ApiError {
    return ApiErrorFromJSONTyped(json, false);
}

export function ApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'retryAfterSeconds': json['retryAfterSeconds'] == null ? undefined : json['retryAfterSeconds'],
    };
}

export function ApiErrorToJSON(json: any): ApiError {
    return ApiErrorToJSONTyped(json, false);
}

export function ApiErrorToJSONTyped(value?: ApiError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'retryAfterSeconds': value['retryAfterSeconds'],
    };
}

