/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Authentication backend used by the account
 * @export
 */
export const AuthProvider = {
    Database: 'DATABASE',
    Google: 'GOOGLE',
    Apple: 'APPLE'
} as const;
export type AuthProvider = typeof AuthProvider[keyof typeof AuthProvider];


export function instanceOfAuthProvider(value: any): boolean {
    for (const key in AuthProvider) {
        if (Object.prototype.hasOwnProperty.call(AuthProvider, key)) {
            if (AuthProvider[key as keyof typeof AuthProvider] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AuthProviderFromJSON(json: any): AuthProvider {
    return AuthProviderFromJSONTyped(json, false);
}

export function AuthProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthProvider {
    return json as AuthProvider;
}

export function AuthProviderToJSON(value?: AuthProvider | null): any {
    return value as any;
}

export function AuthProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): AuthProvider {
    return value as AuthProvider;
}

