/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface CreateSettlementRequest
 */
export interface CreateSettlementRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSettlementRequest
     */
    fromUserId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSettlementRequest
     */
    toUserId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateSettlementRequest
     */
    amount: number;
    /**
     * 
     * @type {Currency}
     * @memberof CreateSettlementRequest
     */
    currency: Currency;
    /**
     * 
     * @type {string}
     * @memberof CreateSettlementRequest
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSettlementRequest
     */
    settledAt?: string;
}



/**
 * Check if a given object implements the CreateSettlementRequest interface.
 */
export function instanceOfCreateSettlementRequest(value: object): value is CreateSettlementRequest {
    if (!('fromUserId' in value) || value['fromUserId'] === undefined) return false;
    if (!('toUserId' in value) || value['toUserId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function CreateSettlementRequestFromJSON(json: any): CreateSettlementRequest {
    return CreateSettlementRequestFromJSONTyped(json, false);
}

export function CreateSettlementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSettlementRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fromUserId': json['fromUserId'],
        'toUserId': json['toUserId'],
        'amount': json['amount'],
        'currency': CurrencyFromJSON(json['currency']),
        'note': json['note'] == null ? undefined : json['note'],
        'settledAt': json['settledAt'] == null ? undefined : json['settledAt'],
    };
}

export function CreateSettlementRequestToJSON(json: any): CreateSettlementRequest {
    return CreateSettlementRequestToJSONTyped(json, false);
}

export function CreateSettlementRequestToJSONTyped(value?: CreateSettlementRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromUserId': value['fromUserId'],
        'toUserId': value['toUserId'],
        'amount': value['amount'],
        'currency': CurrencyToJSON(value['currency']),
        'note': value['note'],
        'settledAt': value['settledAt'],
    };
}

