/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Currency code for an expense
 * @export
 */
export const Currency = {
    Chf: 'CHF',
    Eur: 'EUR',
    Usd: 'USD',
    Gbp: 'GBP'
} as const;
export type Currency = typeof Currency[keyof typeof Currency];


export function CurrencyFromJSON(json: any): Currency {
    return CurrencyFromJSONTyped(json, false);
}

export function CurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Currency {
    return json as Currency;
}

export function CurrencyToJSON(value?: Currency | null): any {
    return value as any;
}

