/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of the expense
 * @export
 */
export const ExpenseStatus = {
    Open: 'OPEN',
    Paid: 'PAID'
} as const;
export type ExpenseStatus = typeof ExpenseStatus[keyof typeof ExpenseStatus];


export function ExpenseStatusFromJSON(json: any): ExpenseStatus {
    return ExpenseStatusFromJSONTyped(json, false);
}

export function ExpenseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseStatus {
    return json as ExpenseStatus;
}

export function ExpenseStatusToJSON(value?: ExpenseStatus | null): any {
    return value as any;
}

