/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { ExpenseShareType } from './ExpenseShareType';
import {
    ExpenseShareTypeFromJSON,
    ExpenseShareTypeFromJSONTyped,
    ExpenseShareTypeToJSON,
    ExpenseShareTypeToJSONTyped,
} from './ExpenseShareType';

/**
 * 
 * @export
 * @interface ExpenseShare
 */
export interface ExpenseShare {
    /**
     * Unique identifier for the share
     * @type {string}
     * @memberof ExpenseShare
     */
    id?: string;
    /**
     * 
     * @type {User}
     * @memberof ExpenseShare
     */
    user: User;
    /**
     * Absolute amount this user owes for the expense
     * @type {number}
     * @memberof ExpenseShare
     */
    amount: number;
    /**
     * 
     * @type {ExpenseShareType}
     * @memberof ExpenseShare
     */
    shareType: ExpenseShareType;
    /**
     * Percent value when shareType=PERCENT (0-100); null otherwise.
     * 
     * @type {number}
     * @memberof ExpenseShare
     */
    shareValue?: number;
}



/**
 * Check if a given object implements the ExpenseShare interface.
 */
export function instanceOfExpenseShare(value: object): value is ExpenseShare {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('shareType' in value) || value['shareType'] === undefined) return false;
    return true;
}

export function ExpenseShareFromJSON(json: any): ExpenseShare {
    return ExpenseShareFromJSONTyped(json, false);
}

export function ExpenseShareFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseShare {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'user': UserFromJSON(json['user']),
        'amount': json['amount'],
        'shareType': ExpenseShareTypeFromJSON(json['shareType']),
        'shareValue': json['shareValue'] == null ? undefined : json['shareValue'],
    };
}

export function ExpenseShareToJSON(json: any): ExpenseShare {
    return ExpenseShareToJSONTyped(json, false);
}

export function ExpenseShareToJSONTyped(value?: ExpenseShare | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user': UserToJSON(value['user']),
        'amount': value['amount'],
        'shareType': ExpenseShareTypeToJSON(value['shareType']),
        'shareValue': value['shareValue'],
    };
}

