/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';
import type { ExpenseShare } from './ExpenseShare';
import {
    ExpenseShareFromJSON,
    ExpenseShareFromJSONTyped,
    ExpenseShareToJSON,
    ExpenseShareToJSONTyped,
} from './ExpenseShare';

/**
 * 
 * @export
 * @interface Expense
 */
export interface Expense {
    /**
     * Unique identifier for the expense
     * @type {string}
     * @memberof Expense
     */
    id?: string;
    /**
     * Description of the expense
     * @type {string}
     * @memberof Expense
     */
    description?: string;
    /**
     * Amount of the expense
     * @type {number}
     * @memberof Expense
     */
    amount: number;
    /**
     * 
     * @type {Currency}
     * @memberof Expense
     */
    currency: Currency;
    /**
     * Date of the expense
     * @type {string}
     * @memberof Expense
     */
    dateOfExpense: string;
    /**
     * Last modified date and time of the expense
     * @type {string}
     * @memberof Expense
     */
    lastModified?: string;
    /**
     * 
     * @type {User}
     * @memberof Expense
     */
    createdBy: User;
    /**
     * 
     * @type {User}
     * @memberof Expense
     */
    paidBy?: User;
    /**
     * Unique identifier of the trip associated with the expense
     * @type {string}
     * @memberof Expense
     */
    tripId: string;
    /**
     * Per-participant breakdown of how this expense is split.
     * @type {Array<ExpenseShare>}
     * @memberof Expense
     */
    shares?: Array<ExpenseShare>;
    /**
     * Original filename of the attached receipt, or null if no receipt
     * has been uploaded. The file itself is served from
     * GET /expenses/{id}/receipt.
     * 
     * @type {string}
     * @memberof Expense
     */
    readonly receiptFilename?: string;
}



/**
 * Check if a given object implements the Expense interface.
 */
export function instanceOfExpense(value: object): value is Expense {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('dateOfExpense' in value) || value['dateOfExpense'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    return true;
}

export function ExpenseFromJSON(json: any): Expense {
    return ExpenseFromJSONTyped(json, false);
}

export function ExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Expense {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'],
        'currency': CurrencyFromJSON(json['currency']),
        'dateOfExpense': json['dateOfExpense'],
        'lastModified': json['lastModified'] == null ? undefined : json['lastModified'],
        'createdBy': UserFromJSON(json['createdBy']),
        'paidBy': json['paidBy'] == null ? undefined : UserFromJSON(json['paidBy']),
        'tripId': json['tripId'],
        'shares': json['shares'] == null ? undefined : ((json['shares'] as Array<any>).map(ExpenseShareFromJSON)),
        'receiptFilename': json['receiptFilename'] == null ? undefined : json['receiptFilename'],
    };
}

export function ExpenseToJSON(json: any): Expense {
    return ExpenseToJSONTyped(json, false);
}

export function ExpenseToJSONTyped(value?: Omit<Expense, 'receiptFilename'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'amount': value['amount'],
        'currency': CurrencyToJSON(value['currency']),
        'dateOfExpense': value['dateOfExpense'],
        'lastModified': value['lastModified'],
        'createdBy': UserToJSON(value['createdBy']),
        'paidBy': UserToJSON(value['paidBy']),
        'tripId': value['tripId'],
        'shares': value['shares'] == null ? undefined : ((value['shares'] as Array<any>).map(ExpenseShareToJSON)),
    };
}

