/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How an expense is split among participants
 * @export
 */
export const ExpenseShareType = {
    Equal: 'EQUAL',
    Exact: 'EXACT',
    Percent: 'PERCENT'
} as const;
export type ExpenseShareType = typeof ExpenseShareType[keyof typeof ExpenseShareType];


export function instanceOfExpenseShareType(value: any): boolean {
    for (const key in ExpenseShareType) {
        if (Object.prototype.hasOwnProperty.call(ExpenseShareType, key)) {
            if (ExpenseShareType[key as keyof typeof ExpenseShareType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ExpenseShareTypeFromJSON(json: any): ExpenseShareType {
    return ExpenseShareTypeFromJSONTyped(json, false);
}

export function ExpenseShareTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseShareType {
    return json as ExpenseShareType;
}

export function ExpenseShareTypeToJSON(value?: ExpenseShareType | null): any {
    return value as any;
}

export function ExpenseShareTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ExpenseShareType {
    return value as ExpenseShareType;
}

