/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
} from './Currency';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Expense
 */
export interface Expense {
    /**
     * Unique identifier for the expense
     * @type {string}
     * @memberof Expense
     */
    id?: string;
    /**
     * Description of the expense
     * @type {string}
     * @memberof Expense
     */
    description?: string;
    /**
     * Amount of the expense
     * @type {number}
     * @memberof Expense
     */
    amount: number;
    /**
     * 
     * @type {Currency}
     * @memberof Expense
     */
    currency: Currency;
    /**
     * Last modified date and time of the expense
     * @type {string}
     * @memberof Expense
     */
    lastModified?: string;
    /**
     * 
     * @type {User}
     * @memberof Expense
     */
    createdBy: User;
    /**
     * 
     * @type {User}
     * @memberof Expense
     */
    paidBy?: User;
    /**
     * Unique identifier of the trip associated with the expense
     * @type {string}
     * @memberof Expense
     */
    tripId: string;
    /**
     * Date of the expense
     * @type {string}
     * @memberof Expense
     */
    dateOfExpense?: string;
}

/**
 * Check if a given object implements the Expense interface.
 */
export function instanceOfExpense(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "currency" in value;
    isInstance = isInstance && "createdBy" in value;
    isInstance = isInstance && "tripId" in value;

    return isInstance;
}

export function ExpenseFromJSON(json: any): Expense {
    return ExpenseFromJSONTyped(json, false);
}

export function ExpenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Expense {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'amount': json['amount'],
        'currency': CurrencyFromJSON(json['currency']),
        'lastModified': !exists(json, 'lastModified') ? undefined : json['lastModified'],
        'createdBy': UserFromJSON(json['createdBy']),
        'paidBy': !exists(json, 'paidBy') ? undefined : UserFromJSON(json['paidBy']),
        'tripId': json['tripId'],
        'dateOfExpense': !exists(json, 'dateOfExpense') ? undefined : json['dateOfExpense'],
    };
}

export function ExpenseToJSON(value?: Expense | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'description': value.description,
        'amount': value.amount,
        'currency': CurrencyToJSON(value.currency),
        'lastModified': value.lastModified,
        'createdBy': UserToJSON(value.createdBy),
        'paidBy': UserToJSON(value.paidBy),
        'tripId': value.tripId,
        'dateOfExpense': value.dateOfExpense,
    };
}

