/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Notification } from './Notification';
import {
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
    NotificationToJSONTyped,
} from './Notification';

/**
 * 
 * @export
 * @interface NotificationList
 */
export interface NotificationList {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof NotificationList
     */
    items: Array<Notification>;
    /**
     * 
     * @type {number}
     * @memberof NotificationList
     */
    unreadCount: number;
}

/**
 * Check if a given object implements the NotificationList interface.
 */
export function instanceOfNotificationList(value: object): value is NotificationList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    return true;
}

export function NotificationListFromJSON(json: any): NotificationList {
    return NotificationListFromJSONTyped(json, false);
}

export function NotificationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(NotificationFromJSON)),
        'unreadCount': json['unreadCount'],
    };
}

export function NotificationListToJSON(json: any): NotificationList {
    return NotificationListToJSONTyped(json, false);
}

export function NotificationListToJSONTyped(value?: NotificationList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(NotificationToJSON)),
        'unreadCount': value['unreadCount'],
    };
}

