/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationType } from './NotificationType';
import {
    NotificationTypeFromJSON,
    NotificationTypeFromJSONTyped,
    NotificationTypeToJSON,
    NotificationTypeToJSONTyped,
} from './NotificationType';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    id: string;
    /**
     * 
     * @type {NotificationType}
     * @memberof Notification
     */
    type: NotificationType;
    /**
     * Trip referenced by this notification, if any
     * @type {string}
     * @memberof Notification
     */
    tripId?: string;
    /**
     * Expense referenced by this notification, if any
     * @type {string}
     * @memberof Notification
     */
    expenseId?: string;
    /**
     * User who caused the event, if applicable
     * @type {string}
     * @memberof Notification
     */
    actorUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof Notification
     */
    read: boolean;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    createdAt: string;
}



/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('read' in value) || value['read'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': NotificationTypeFromJSON(json['type']),
        'tripId': json['tripId'] == null ? undefined : json['tripId'],
        'expenseId': json['expenseId'] == null ? undefined : json['expenseId'],
        'actorUserId': json['actorUserId'] == null ? undefined : json['actorUserId'],
        'title': json['title'],
        'message': json['message'],
        'read': json['read'],
        'createdAt': json['createdAt'],
    };
}

export function NotificationToJSON(json: any): Notification {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': NotificationTypeToJSON(value['type']),
        'tripId': value['tripId'],
        'expenseId': value['expenseId'],
        'actorUserId': value['actorUserId'],
        'title': value['title'],
        'message': value['message'],
        'read': value['read'],
        'createdAt': value['createdAt'],
    };
}

