/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface Settlement
 */
export interface Settlement {
    /**
     * Unique identifier for the settlement
     * @type {string}
     * @memberof Settlement
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Settlement
     */
    tripId: string;
    /**
     * 
     * @type {User}
     * @memberof Settlement
     */
    fromUser: User;
    /**
     * 
     * @type {User}
     * @memberof Settlement
     */
    toUser: User;
    /**
     * 
     * @type {number}
     * @memberof Settlement
     */
    amount: number;
    /**
     * 
     * @type {Currency}
     * @memberof Settlement
     */
    currency: Currency;
    /**
     * 
     * @type {string}
     * @memberof Settlement
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof Settlement
     */
    settledAt: string;
    /**
     * 
     * @type {string}
     * @memberof Settlement
     */
    createdAt?: string;
}



/**
 * Check if a given object implements the Settlement interface.
 */
export function instanceOfSettlement(value: object): value is Settlement {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    if (!('fromUser' in value) || value['fromUser'] === undefined) return false;
    if (!('toUser' in value) || value['toUser'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('settledAt' in value) || value['settledAt'] === undefined) return false;
    return true;
}

export function SettlementFromJSON(json: any): Settlement {
    return SettlementFromJSONTyped(json, false);
}

export function SettlementFromJSONTyped(json: any, ignoreDiscriminator: boolean): Settlement {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'tripId': json['tripId'],
        'fromUser': UserFromJSON(json['fromUser']),
        'toUser': UserFromJSON(json['toUser']),
        'amount': json['amount'],
        'currency': CurrencyFromJSON(json['currency']),
        'note': json['note'] == null ? undefined : json['note'],
        'settledAt': json['settledAt'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function SettlementToJSON(json: any): Settlement {
    return SettlementToJSONTyped(json, false);
}

export function SettlementToJSONTyped(value?: Settlement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tripId': value['tripId'],
        'fromUser': UserToJSON(value['fromUser']),
        'toUser': UserToJSON(value['toUser']),
        'amount': value['amount'],
        'currency': CurrencyToJSON(value['currency']),
        'note': value['note'],
        'settledAt': value['settledAt'],
        'createdAt': value['createdAt'],
    };
}

