/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInRequest
 */
export interface SignInRequest {
    /**
     * Email address or username for authentication
     * @type {string}
     * @memberof SignInRequest
     */
    identifier: string;
    /**
     * Password for authentication
     * @type {string}
     * @memberof SignInRequest
     */
    password: string;
}

/**
 * Check if a given object implements the SignInRequest interface.
 */
export function instanceOfSignInRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identifier" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function SignInRequestFromJSON(json: any): SignInRequest {
    return SignInRequestFromJSONTyped(json, false);
}

export function SignInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'password': json['password'],
    };
}

export function SignInRequestToJSON(value?: SignInRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'password': value.password,
    };
}

