/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface SuggestedSettlement
 */
export interface SuggestedSettlement {
    /**
     * 
     * @type {User}
     * @memberof SuggestedSettlement
     */
    fromUser: User;
    /**
     * 
     * @type {User}
     * @memberof SuggestedSettlement
     */
    toUser: User;
    /**
     * 
     * @type {Currency}
     * @memberof SuggestedSettlement
     */
    currency: Currency;
    /**
     * 
     * @type {number}
     * @memberof SuggestedSettlement
     */
    amount: number;
}



/**
 * Check if a given object implements the SuggestedSettlement interface.
 */
export function instanceOfSuggestedSettlement(value: object): value is SuggestedSettlement {
    if (!('fromUser' in value) || value['fromUser'] === undefined) return false;
    if (!('toUser' in value) || value['toUser'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function SuggestedSettlementFromJSON(json: any): SuggestedSettlement {
    return SuggestedSettlementFromJSONTyped(json, false);
}

export function SuggestedSettlementFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestedSettlement {
    if (json == null) {
        return json;
    }
    return {
        
        'fromUser': UserFromJSON(json['fromUser']),
        'toUser': UserFromJSON(json['toUser']),
        'currency': CurrencyFromJSON(json['currency']),
        'amount': json['amount'],
    };
}

export function SuggestedSettlementToJSON(json: any): SuggestedSettlement {
    return SuggestedSettlementToJSONTyped(json, false);
}

export function SuggestedSettlementToJSONTyped(value?: SuggestedSettlement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromUser': UserToJSON(value['fromUser']),
        'toUser': UserToJSON(value['toUser']),
        'currency': CurrencyToJSON(value['currency']),
        'amount': value['amount'],
    };
}

