/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserBalance } from './UserBalance';
import {
    UserBalanceFromJSON,
    UserBalanceFromJSONTyped,
    UserBalanceToJSON,
    UserBalanceToJSONTyped,
} from './UserBalance';
import type { SuggestedSettlement } from './SuggestedSettlement';
import {
    SuggestedSettlementFromJSON,
    SuggestedSettlementFromJSONTyped,
    SuggestedSettlementToJSON,
    SuggestedSettlementToJSONTyped,
} from './SuggestedSettlement';

/**
 * 
 * @export
 * @interface TripBalances
 */
export interface TripBalances {
    /**
     * 
     * @type {string}
     * @memberof TripBalances
     */
    tripId: string;
    /**
     * 
     * @type {Array<UserBalance>}
     * @memberof TripBalances
     */
    balances: Array<UserBalance>;
    /**
     * 
     * @type {Array<SuggestedSettlement>}
     * @memberof TripBalances
     */
    suggestedSettlements: Array<SuggestedSettlement>;
}

/**
 * Check if a given object implements the TripBalances interface.
 */
export function instanceOfTripBalances(value: object): value is TripBalances {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    if (!('balances' in value) || value['balances'] === undefined) return false;
    if (!('suggestedSettlements' in value) || value['suggestedSettlements'] === undefined) return false;
    return true;
}

export function TripBalancesFromJSON(json: any): TripBalances {
    return TripBalancesFromJSONTyped(json, false);
}

export function TripBalancesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripBalances {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
        'balances': ((json['balances'] as Array<any>).map(UserBalanceFromJSON)),
        'suggestedSettlements': ((json['suggestedSettlements'] as Array<any>).map(SuggestedSettlementFromJSON)),
    };
}

export function TripBalancesToJSON(json: any): TripBalances {
    return TripBalancesToJSONTyped(json, false);
}

export function TripBalancesToJSONTyped(value?: TripBalances | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'balances': ((value['balances'] as Array<any>).map(UserBalanceToJSON)),
        'suggestedSettlements': ((value['suggestedSettlements'] as Array<any>).map(SuggestedSettlementToJSON)),
    };
}

