/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Expense } from './Expense';
import {
    ExpenseFromJSON,
    ExpenseFromJSONTyped,
    ExpenseToJSON,
    ExpenseToJSONTyped,
} from './Expense';
import type { TripStatus } from './TripStatus';
import {
    TripStatusFromJSON,
    TripStatusFromJSONTyped,
    TripStatusToJSON,
    TripStatusToJSONTyped,
} from './TripStatus';

/**
 * 
 * @export
 * @interface Trip
 */
export interface Trip {
    /**
     * Unique identifier for the trip
     * @type {string}
     * @memberof Trip
     */
    id?: string;
    /**
     * Name of the trip
     * @type {string}
     * @memberof Trip
     */
    name?: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof Trip
     */
    participants: Array<User>;
    /**
     * Destination of the trip
     * @type {string}
     * @memberof Trip
     */
    destination: string;
    /**
     * Start time of the trip
     * @type {string}
     * @memberof Trip
     */
    startTime: string;
    /**
     * End time of the trip
     * @type {string}
     * @memberof Trip
     */
    endTime?: string;
    /**
     * Description of the trip
     * @type {string}
     * @memberof Trip
     */
    description?: string;
    /**
     * 
     * @type {TripStatus}
     * @memberof Trip
     */
    status: TripStatus;
    /**
     * 
     * @type {Array<Expense>}
     * @memberof Trip
     */
    expenses?: Array<Expense>;
}



/**
 * Check if a given object implements the Trip interface.
 */
export function instanceOfTrip(value: object): value is Trip {
    if (!('participants' in value) || value['participants'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TripFromJSON(json: any): Trip {
    return TripFromJSONTyped(json, false);
}

export function TripFromJSONTyped(json: any, ignoreDiscriminator: boolean): Trip {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'participants': ((json['participants'] as Array<any>).map(UserFromJSON)),
        'destination': json['destination'],
        'startTime': json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': TripStatusFromJSON(json['status']),
        'expenses': json['expenses'] == null ? undefined : ((json['expenses'] as Array<any>).map(ExpenseFromJSON)),
    };
}

export function TripToJSON(json: any): Trip {
    return TripToJSONTyped(json, false);
}

export function TripToJSONTyped(value?: Trip | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'participants': ((value['participants'] as Array<any>).map(UserToJSON)),
        'destination': value['destination'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'description': value['description'],
        'status': TripStatusToJSON(value['status']),
        'expenses': value['expenses'] == null ? undefined : ((value['expenses'] as Array<any>).map(ExpenseToJSON)),
    };
}

