/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripInviteResponse
 */
export interface TripInviteResponse {
    /**
     * Opaque, reusable invite token. Append to the frontend join path to build the shareable link.
     * @type {string}
     * @memberof TripInviteResponse
     */
    token: string;
}

/**
 * Check if a given object implements the TripInviteResponse interface.
 */
export function instanceOfTripInviteResponse(value: object): value is TripInviteResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function TripInviteResponseFromJSON(json: any): TripInviteResponse {
    return TripInviteResponseFromJSONTyped(json, false);
}

export function TripInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripInviteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function TripInviteResponseToJSON(json: any): TripInviteResponse {
    return TripInviteResponseToJSONTyped(json, false);
}

export function TripInviteResponseToJSONTyped(value?: TripInviteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

