/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TripStatus } from './TripStatus';
import {
    TripStatusFromJSON,
    TripStatusFromJSONTyped,
    TripStatusToJSON,
    TripStatusToJSONTyped,
} from './TripStatus';

/**
 * 
 * @export
 * @interface TripInvitePreview
 */
export interface TripInvitePreview {
    /**
     * 
     * @type {string}
     * @memberof TripInvitePreview
     */
    tripId: string;
    /**
     * Name of the trip, if set
     * @type {string}
     * @memberof TripInvitePreview
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TripInvitePreview
     */
    destination: string;
    /**
     * 
     * @type {string}
     * @memberof TripInvitePreview
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof TripInvitePreview
     */
    endTime?: string;
    /**
     * 
     * @type {TripStatus}
     * @memberof TripInvitePreview
     */
    status: TripStatus;
    /**
     * Display name of the trip creator, if known
     * @type {string}
     * @memberof TripInvitePreview
     */
    invitedByName?: string;
    /**
     * Number of people currently on the trip
     * @type {number}
     * @memberof TripInvitePreview
     */
    participantCount: number;
    /**
     * True if the current user is already on this trip
     * @type {boolean}
     * @memberof TripInvitePreview
     */
    alreadyParticipant: boolean;
}



/**
 * Check if a given object implements the TripInvitePreview interface.
 */
export function instanceOfTripInvitePreview(value: object): value is TripInvitePreview {
    if (!('tripId' in value) || value['tripId'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('participantCount' in value) || value['participantCount'] === undefined) return false;
    if (!('alreadyParticipant' in value) || value['alreadyParticipant'] === undefined) return false;
    return true;
}

export function TripInvitePreviewFromJSON(json: any): TripInvitePreview {
    return TripInvitePreviewFromJSONTyped(json, false);
}

export function TripInvitePreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripInvitePreview {
    if (json == null) {
        return json;
    }
    return {
        
        'tripId': json['tripId'],
        'name': json['name'] == null ? undefined : json['name'],
        'destination': json['destination'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'status': TripStatusFromJSON(json['status']),
        'invitedByName': json['invitedByName'] == null ? undefined : json['invitedByName'],
        'participantCount': json['participantCount'],
        'alreadyParticipant': json['alreadyParticipant'],
    };
}

export function TripInvitePreviewToJSON(json: any): TripInvitePreview {
    return TripInvitePreviewToJSONTyped(json, false);
}

export function TripInvitePreviewToJSONTyped(value?: TripInvitePreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripId': value['tripId'],
        'name': value['name'],
        'destination': value['destination'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'status': TripStatusToJSON(value['status']),
        'invitedByName': value['invitedByName'],
        'participantCount': value['participantCount'],
        'alreadyParticipant': value['alreadyParticipant'],
    };
}

