/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * 
 * @export
 * @interface UserBalance
 */
export interface UserBalance {
    /**
     * 
     * @type {User}
     * @memberof UserBalance
     */
    user: User;
    /**
     * 
     * @type {Currency}
     * @memberof UserBalance
     */
    currency: Currency;
    /**
     * Net balance for this user in this currency: positive = is owed
     * money; negative = owes money.
     * 
     * @type {number}
     * @memberof UserBalance
     */
    net: number;
}



/**
 * Check if a given object implements the UserBalance interface.
 */
export function instanceOfUserBalance(value: object): value is UserBalance {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('net' in value) || value['net'] === undefined) return false;
    return true;
}

export function UserBalanceFromJSON(json: any): UserBalance {
    return UserBalanceFromJSONTyped(json, false);
}

export function UserBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBalance {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'currency': CurrencyFromJSON(json['currency']),
        'net': json['net'],
    };
}

export function UserBalanceToJSON(json: any): UserBalance {
    return UserBalanceToJSONTyped(json, false);
}

export function UserBalanceToJSONTyped(value?: UserBalance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserToJSON(value['user']),
        'currency': CurrencyToJSON(value['currency']),
        'net': value['net'],
    };
}

