/* tslint:disable */
/* eslint-disable */
/**
 * TravelSync API
 * ## TravelSync API Documentation This API provides endpoints for managing travel itineraries, including creating, updating, and retrieving travel plans. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: pniecke@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRole } from './UserRole';
import {
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
    UserRoleToJSONTyped,
} from './UserRole';
import type { AuthProvider } from './AuthProvider';
import {
    AuthProviderFromJSON,
    AuthProviderFromJSONTyped,
    AuthProviderToJSON,
    AuthProviderToJSONTyped,
} from './AuthProvider';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * Unique identifier for the user
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * Username of the user
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * First name of the user
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * Last name of the user
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * Email address of the user
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * Mobile phone number of the user
     * @type {string}
     * @memberof User
     */
    mobile?: string;
    /**
     * Locale of the user
     * @type {string}
     * @memberof User
     */
    locale?: string;
    /**
     * 
     * @type {Array<UserRole>}
     * @memberof User
     */
    roles?: Array<UserRole>;
    /**
     * Password of the user (write-only)
     * @type {string}
     * @memberof User
     */
    password?: string;
    /**
     * 
     * @type {AuthProvider}
     * @memberof User
     */
    authProvider?: AuthProvider;
}



/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'email': json['email'] == null ? undefined : json['email'],
        'mobile': json['mobile'] == null ? undefined : json['mobile'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(UserRoleFromJSON)),
        'password': json['password'] == null ? undefined : json['password'],
        'authProvider': json['authProvider'] == null ? undefined : AuthProviderFromJSON(json['authProvider']),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
        'mobile': value['mobile'],
        'locale': value['locale'],
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(UserRoleToJSON)),
        'password': value['password'],
        'authProvider': AuthProviderToJSON(value['authProvider']),
    };
}

