/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.paullouis.travelsync.controller

import com.paullouis.travelsync.model.generated.ApiError
import com.paullouis.travelsync.model.generated.ChangePasswordRequest
import com.paullouis.travelsync.model.generated.MeResponse
import com.paullouis.travelsync.model.generated.MessageResponse
import com.paullouis.travelsync.model.generated.SignInRequest
import com.paullouis.travelsync.model.generated.SignUpRequest
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface AuthenticationApi {

    @Operation(
        tags = ["Authentication",],
        summary = "Change the password of the currently logged-in user",
        operationId = "changePassword",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Password changed successfully"),
            ApiResponse(responseCode = "400", description = "Bad Request - new password fails policy", content = [Content(schema = Schema(implementation = ApiError::class))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - current password incorrect or no session", content = [Content(schema = Schema(implementation = ApiError::class))])
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/auth/change-password"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun changePassword(@Parameter(description = "", required = true) @Valid @RequestBody changePasswordRequest: ChangePasswordRequest): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Authentication",],
        summary = "End the current session",
        operationId = "logout",
        description = """Idempotent — succeeds whether or not a session exists.""",
        responses = [
            ApiResponse(responseCode = "204", description = "Session ended (or no session was active)")
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/auth/logout"]
    )
    fun logout(): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Authentication",],
        summary = "Authenticate a local-database account and create a session",
        operationId = "signIn",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Authenticated; session cookie issued", content = [Content(schema = Schema(implementation = MeResponse::class))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - bad credentials", content = [Content(schema = Schema(implementation = ApiError::class))]),
            ApiResponse(responseCode = "429", description = "Too Many Requests - account locked or IP throttled", content = [Content(schema = Schema(implementation = ApiError::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/auth/signin"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun signIn(@Parameter(description = "", required = true) @Valid @RequestBody signInRequest: SignInRequest): ResponseEntity<MeResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Authentication",],
        summary = "Register a new local-database account",
        operationId = "signUp",
        description = """""",
        responses = [
            ApiResponse(responseCode = "201", description = "Account created successfully", content = [Content(schema = Schema(implementation = MessageResponse::class))]),
            ApiResponse(responseCode = "400", description = "Bad Request - invalid signup data", content = [Content(schema = Schema(implementation = ApiError::class))]),
            ApiResponse(responseCode = "409", description = "Conflict - username or email already in use", content = [Content(schema = Schema(implementation = ApiError::class))]),
            ApiResponse(responseCode = "429", description = "Too Many Requests - signup rate limit exceeded", content = [Content(schema = Schema(implementation = ApiError::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/auth/signup"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun signUp(@Parameter(description = "", required = true) @Valid @RequestBody signUpRequest: SignUpRequest): ResponseEntity<MessageResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
