/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.paullouis.travelsync.controller

import com.paullouis.travelsync.model.generated.Expense
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired


import kotlin.collections.List
import kotlin.collections.Map

@RequestMapping("\${api.base-path:/api}")
interface ExpenseApi {

    @Operation(
        summary = "Create a new expense",
        operationId = "createExpense",
        description = """""",
        responses = [
            ApiResponse(responseCode = "201", description = "Expense created successfully", content = [Content(schema = Schema(implementation = Expense::class))]),
            ApiResponse(responseCode = "400", description = "Bad Request - Invalid expense data"),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/expenses"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createExpense(@Parameter(description = "", required = true)  @RequestBody expense: kotlin.collections.List<Expense>): ResponseEntity<List<Expense>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        summary = "Get expenses with optional filtering",
        operationId = "getExpenses",
        description = """Returns a list of expenses, optionally filtered by creator or payer""",
        responses = [
            ApiResponse(responseCode = "200", description = "List of expenses", content = [Content(schema = Schema(implementation = Expense::class))])
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/expenses"],
            produces = ["application/json"]
    )
    fun getExpenses(@Parameter(description = "When true, return only expenses created by the current user") @RequestParam(value = "createdBy", required = false) createdBy: kotlin.Boolean?,@Parameter(description = "When true, return only expenses paid by the current user") @RequestParam(value = "paidBy", required = false) paidBy: kotlin.Boolean?): ResponseEntity<List<Expense>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
