/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.paullouis.travelsync.controller

import com.paullouis.travelsync.model.generated.ApiError
import com.paullouis.travelsync.model.generated.Expense
import com.paullouis.travelsync.model.generated.ExpenseShare
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface ExpenseApi {

    @Operation(
        tags = ["Expense",],
        summary = "Create a new expense",
        operationId = "createExpense",
        description = """""",
        responses = [
            ApiResponse(responseCode = "201", description = "Expense created successfully", content = [Content(array = ArraySchema(schema = Schema(implementation = Expense::class)))]),
            ApiResponse(responseCode = "400", description = "Bad Request - Invalid expense data"),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/expenses"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createExpense(@Parameter(description = "", required = true) @Valid @RequestBody expense: kotlin.collections.List<Expense>): ResponseEntity<List<Expense>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Expense",],
        summary = "Delete an expense (cascades shares)",
        operationId = "deleteExpense",
        description = """""",
        responses = [
            ApiResponse(responseCode = "204", description = "Expense deleted"),
            ApiResponse(responseCode = "403", description = "Forbidden"),
            ApiResponse(responseCode = "404", description = "Expense not found")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.DELETE],
            value = ["/expenses/{id}"]
    )
    fun deleteExpense(@Parameter(description = "", required = true) @PathVariable("id") id: java.util.UUID): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Expense",],
        summary = "Get a single expense by id",
        operationId = "getExpense",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "The expense", content = [Content(schema = Schema(implementation = Expense::class))]),
            ApiResponse(responseCode = "404", description = "Expense not found", content = [Content(schema = Schema(implementation = ApiError::class))])
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/expenses/{id}"],
            produces = ["application/json"]
    )
    fun getExpense(@Parameter(description = "", required = true) @PathVariable("id") id: java.util.UUID): ResponseEntity<Expense> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Expense",],
        summary = "List all shares for an expense",
        operationId = "getExpenseShares",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Shares for this expense", content = [Content(array = ArraySchema(schema = Schema(implementation = ExpenseShare::class)))]),
            ApiResponse(responseCode = "404", description = "Expense not found")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/expenses/{id}/shares"],
            produces = ["application/json"]
    )
    fun getExpenseShares(@Parameter(description = "", required = true) @PathVariable("id") id: java.util.UUID): ResponseEntity<List<ExpenseShare>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Expense",],
        summary = "Get expenses with optional filtering",
        operationId = "getExpenses",
        description = """Returns a list of expenses, optionally filtered by creator, payer or trip""",
        responses = [
            ApiResponse(responseCode = "200", description = "List of expenses", content = [Content(array = ArraySchema(schema = Schema(implementation = Expense::class)))])
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/expenses"],
            produces = ["application/json"]
    )
    fun getExpenses(@Parameter(description = "When true, return only expenses created by the current user") @Valid @RequestParam(value = "createdBy", required = false) createdBy: kotlin.Boolean?,@Parameter(description = "When true, return only expenses paid by the current user") @Valid @RequestParam(value = "paidBy", required = false) paidBy: kotlin.Boolean?,@Parameter(description = "Filter expenses to a single trip") @Valid @RequestParam(value = "tripId", required = false) tripId: java.util.UUID?): ResponseEntity<List<Expense>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Expense",],
        summary = "Replace all shares for an expense",
        operationId = "updateExpenseShares",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Updated shares", content = [Content(array = ArraySchema(schema = Schema(implementation = ExpenseShare::class)))]),
            ApiResponse(responseCode = "400", description = "Invalid shares (sum mismatch, non-participant, etc.)", content = [Content(schema = Schema(implementation = ApiError::class))]),
            ApiResponse(responseCode = "403", description = "Forbidden"),
            ApiResponse(responseCode = "404", description = "Expense not found")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.PUT],
            value = ["/expenses/{id}/shares"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun updateExpenseShares(@Parameter(description = "", required = true) @PathVariable("id") id: java.util.UUID,@Parameter(description = "", required = true) @Valid @RequestBody expenseShare: kotlin.collections.List<ExpenseShare>): ResponseEntity<List<ExpenseShare>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
