/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.paullouis.travelsync.controller

import com.paullouis.travelsync.model.generated.Notification
import com.paullouis.travelsync.model.generated.NotificationList
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface NotificationApi {

    @Operation(
        tags = ["Notification",],
        summary = "List notifications for the current user",
        operationId = "getNotifications",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Notifications for the authenticated user, newest first", content = [Content(schema = Schema(implementation = NotificationList::class))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/notifications"],
            produces = ["application/json"]
    )
    fun getNotifications(@Parameter(description = "", schema = Schema(defaultValue = "false")) @Valid @RequestParam(value = "unreadOnly", required = false, defaultValue = "false") unreadOnly: kotlin.Boolean,@Min(1) @Max(200) @Parameter(description = "", schema = Schema(defaultValue = "50")) @Valid @RequestParam(value = "limit", required = false, defaultValue = "50") limit: kotlin.Int): ResponseEntity<NotificationList> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Notification",],
        summary = "Mark all of the current user's unread notifications as read",
        operationId = "markAllNotificationsRead",
        description = """""",
        responses = [
            ApiResponse(responseCode = "204", description = "All notifications marked as read")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/notifications/read-all"]
    )
    fun markAllNotificationsRead(): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Notification",],
        summary = "Mark a single notification as read (idempotent)",
        operationId = "markNotificationRead",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "The updated notification", content = [Content(schema = Schema(implementation = Notification::class))]),
            ApiResponse(responseCode = "403", description = "Forbidden - notification belongs to another user"),
            ApiResponse(responseCode = "404", description = "Notification not found")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/notifications/{id}/read"],
            produces = ["application/json"]
    )
    fun markNotificationRead(@Parameter(description = "", required = true) @PathVariable("id") id: java.util.UUID): ResponseEntity<Notification> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
