/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.paullouis.travelsync.controller

import com.paullouis.travelsync.model.generated.ApiError
import com.paullouis.travelsync.model.generated.CreateSettlementRequest
import com.paullouis.travelsync.model.generated.Settlement
import com.paullouis.travelsync.model.generated.Trip
import com.paullouis.travelsync.model.generated.TripBalances
import com.paullouis.travelsync.model.generated.TripInvitePreview
import com.paullouis.travelsync.model.generated.TripInviteResponse
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface TripApi {

    @Operation(
        tags = ["Trip",],
        summary = "Record a settlement (cash payment between participants)",
        operationId = "createSettlement",
        description = """""",
        responses = [
            ApiResponse(responseCode = "201", description = "Settlement created", content = [Content(schema = Schema(implementation = Settlement::class))]),
            ApiResponse(responseCode = "400", description = "Invalid settlement", content = [Content(schema = Schema(implementation = ApiError::class))]),
            ApiResponse(responseCode = "403", description = "Forbidden")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/trips/{id}/settlements"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createSettlement(@Parameter(description = "", required = true) @PathVariable("id") id: java.util.UUID,@Parameter(description = "", required = true) @Valid @RequestBody createSettlementRequest: CreateSettlementRequest): ResponseEntity<Settlement> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Create a new trip",
        operationId = "createTrip",
        description = """""",
        responses = [
            ApiResponse(responseCode = "201", description = "Trip created successfully", content = [Content(array = ArraySchema(schema = Schema(implementation = Trip::class)))]),
            ApiResponse(responseCode = "400", description = "Bad Request - Invalid trip data"),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/trips"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun createTrip(@Parameter(description = "", required = true) @Valid @RequestBody trip: kotlin.collections.List<Trip>): ResponseEntity<List<Trip>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Create or fetch the shareable invite link for a trip",
        operationId = "createTripInvite",
        description = """Returns the trip's reusable invite token, minting one on first call.
Anyone who opens the resulting link (and is or becomes a signed-in
user) can join the trip. Only existing participants may fetch it.
""",
        responses = [
            ApiResponse(responseCode = "200", description = "Invite token", content = [Content(schema = Schema(implementation = TripInviteResponse::class))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required"),
            ApiResponse(responseCode = "403", description = "Forbidden - Not a participant"),
            ApiResponse(responseCode = "404", description = "Trip not found")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/trips/{id}/invite"],
            produces = ["application/json"]
    )
    fun createTripInvite(@Parameter(description = "Unique identifier of the trip", required = true) @PathVariable("id") id: java.util.UUID): ResponseEntity<TripInviteResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Delete a recorded settlement",
        operationId = "deleteSettlement",
        description = """""",
        responses = [
            ApiResponse(responseCode = "204", description = "Deleted"),
            ApiResponse(responseCode = "403", description = "Forbidden"),
            ApiResponse(responseCode = "404", description = "Settlement not found")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.DELETE],
            value = ["/trips/{id}/settlements/{settlementId}"]
    )
    fun deleteSettlement(@Parameter(description = "", required = true) @PathVariable("id") id: java.util.UUID,@Parameter(description = "", required = true) @PathVariable("settlementId") settlementId: java.util.UUID): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Delete a trip",
        operationId = "deleteTrip",
        description = """Hard-deletes a trip. Only the trip's creator may delete, and only when
the trip has no recorded expenses or settlements — otherwise cancel it
instead.
""",
        responses = [
            ApiResponse(responseCode = "204", description = "Deleted"),
            ApiResponse(responseCode = "403", description = "Forbidden - Not the trip's creator"),
            ApiResponse(responseCode = "404", description = "Trip not found"),
            ApiResponse(responseCode = "409", description = "Trip has expenses or settlements; cancel instead", content = [Content(schema = Schema(implementation = ApiError::class))])
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.DELETE],
            value = ["/trips/{id}"],
            produces = ["application/json"]
    )
    fun deleteTrip(@Parameter(description = "Unique identifier of the trip", required = true) @PathVariable("id") id: java.util.UUID): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Get net balances and suggested settlements for a trip",
        operationId = "getTripBalances",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Per-currency net balances and suggested settlements", content = [Content(schema = Schema(implementation = TripBalances::class))]),
            ApiResponse(responseCode = "403", description = "Forbidden"),
            ApiResponse(responseCode = "404", description = "Trip not found")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/trips/{id}/balances"],
            produces = ["application/json"]
    )
    fun getTripBalances(@Parameter(description = "", required = true) @PathVariable("id") id: java.util.UUID): ResponseEntity<TripBalances> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Get a single trip",
        operationId = "getTripById",
        description = """Returns the trip if the current user is a participant.""",
        responses = [
            ApiResponse(responseCode = "200", description = "Trip", content = [Content(schema = Schema(implementation = Trip::class))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required"),
            ApiResponse(responseCode = "403", description = "Forbidden - Not a participant"),
            ApiResponse(responseCode = "404", description = "Trip not found")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/trips/{id}"],
            produces = ["application/json"]
    )
    fun getTripById(@Parameter(description = "Unique identifier of the trip", required = true) @PathVariable("id") id: java.util.UUID): ResponseEntity<Trip> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Preview a trip invite",
        operationId = "getTripInvitePreview",
        description = """Returns a lightweight summary of the trip an invite points at, for the
join landing page. Requires authentication so non-users are routed
through sign-up first.
""",
        responses = [
            ApiResponse(responseCode = "200", description = "Invite preview", content = [Content(schema = Schema(implementation = TripInvitePreview::class))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required"),
            ApiResponse(responseCode = "404", description = "Invite not found")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/trips/invites/{token}"],
            produces = ["application/json"]
    )
    fun getTripInvitePreview(@Parameter(description = "Opaque invite token", required = true) @PathVariable("token") token: kotlin.String): ResponseEntity<TripInvitePreview> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "List all settlements for a trip",
        operationId = "getTripSettlements",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Settlements for this trip", content = [Content(array = ArraySchema(schema = Schema(implementation = Settlement::class)))])
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/trips/{id}/settlements"],
            produces = ["application/json"]
    )
    fun getTripSettlements(@Parameter(description = "", required = true) @PathVariable("id") id: java.util.UUID): ResponseEntity<List<Settlement>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Get Trips for Logged-in User",
        operationId = "getTripsByLoggedInUser",
        description = """Retrieves a list of trips associated with the currently authenticated user.""",
        responses = [
            ApiResponse(responseCode = "200", description = "List of trips for the logged-in user", content = [Content(array = ArraySchema(schema = Schema(implementation = Trip::class)))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/trips/my-trips"],
            produces = ["application/json"]
    )
    fun getTripsByLoggedInUser(): ResponseEntity<List<Trip>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Join a trip via an invite link",
        operationId = "joinTripViaInvite",
        description = """Adds the current user to the trip the token points at. Idempotent for
users who are already participants. Rejected for cancelled trips.
""",
        responses = [
            ApiResponse(responseCode = "200", description = "Joined trip", content = [Content(schema = Schema(implementation = Trip::class))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required"),
            ApiResponse(responseCode = "404", description = "Invite not found"),
            ApiResponse(responseCode = "409", description = "Trip cannot be joined (e.g. cancelled)", content = [Content(schema = Schema(implementation = ApiError::class))])
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/trips/invites/{token}/join"],
            produces = ["application/json"]
    )
    fun joinTripViaInvite(@Parameter(description = "Opaque invite token", required = true) @PathVariable("token") token: kotlin.String): ResponseEntity<Trip> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Trip",],
        summary = "Update an existing trip",
        operationId = "updateTrip",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Trip updated successfully", content = [Content(schema = Schema(implementation = Trip::class))]),
            ApiResponse(responseCode = "400", description = "Bad Request - Invalid trip data"),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required"),
            ApiResponse(responseCode = "409", description = "Conflict (e.g. removing a participant with expenses)", content = [Content(schema = Schema(implementation = ApiError::class))])
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.PUT],
            value = ["/trips/{id}"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun updateTrip(@Parameter(description = "Unique identifier of the trip to update", required = true) @PathVariable("id") id: java.util.UUID,@Parameter(description = "", required = true) @Valid @RequestBody trip: Trip): ResponseEntity<Trip> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
