/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.paullouis.travelsync.controller

import com.paullouis.travelsync.model.generated.User
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface UserApi {

    @Operation(
        tags = ["User",],
        summary = "Get all users",
        operationId = "getAllUsers",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "List of all users", content = [Content(array = ArraySchema(schema = Schema(implementation = User::class)))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/users"],
            produces = ["application/json"]
    )
    fun getAllUsers(): ResponseEntity<List<User>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["User",],
        summary = "Get the currently logged-in user",
        operationId = "getLoggedInUser",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Successfully retrieved the logged-in user", content = [Content(schema = Schema(implementation = User::class))]),
            ApiResponse(responseCode = "401", description = "Unauthorized - Authentication required")
        ],
        security = [ SecurityRequirement(name = "OidcAuth") ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/user/me"],
            produces = ["application/json"]
    )
    fun getLoggedInUser(): ResponseEntity<User> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
